version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports: 
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    restart: always
    depends_on:
      - elasticsearch
    environment: 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
    ports: 
      - "5601:5601"

  logstash:
    image: custom_logstash
    build: ./logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
   
